name: gold-price-predictor
on:
   schedule:
    - cron: '0 * * * *'  
   workflow_dispatch:
jobs:
  schedule_pipelines:
    runs-on: self-hosted
    permissions:
      pages: write
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
       
      - name: execute python workflows from bash script
        
        run: |
          jupyter nbconvert --to notebook --execute features.ipynb
          jupyter nbconvert --to notebook --execute inference.ipynb
      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Hourly gold price Predection Dashboard published"
          commit_options: '--no-verify --signoff'
          file_pattern: 'docs/plot.png'
          repository: .
          status_options: '--untracked-files=no'
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          push_options: '--force'
